on:
  push:
    branches:
      - osagnostic
      - gh-actions
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-10.15]
        include:
          - os: macos-latest
          - os: macos-10.15
    steps:
    - uses: actions/checkout@osagnostic
    - name: Build
      run: sh ./bundledApps/MAKEFILE.sh
